### DAY 3

In [ ]:
## Assignment 1

In [2]:
import pandas as pd
import numpy as np

In [3]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[4,5,6,7,8]

In [4]:
arr1=np.array([lst1,lst2,lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [12]:
arr1[1:,2:]

array([[4, 5, 6],
       [6, 7, 8]])

In [ ]:
## Assignment 2

In [21]:
df=pd.DataFrame(np.random.randn(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column1','Column2','Column3','Column4'])
df.head()

Column1   Column2   Column3   Column4
Row1 -0.679423 -1.437182  0.869358  0.321864
Row2  0.601075  0.845697 -0.279930 -0.561764
Row3 -0.387098  0.238974 -0.284162 -0.737501
Row4  2.161435 -0.344307 -0.277027 -0.292289
Row5  0.429979 -0.921085  0.524528 -0.164013

In [22]:
df['Column3']

Row1    0.869358
Row2   -0.279930
Row3   -0.284162
Row4   -0.277027
Row5    0.524528
Name: Column3, dtype: float64

In [24]:
df[['Column2','Column4']]

Column2   Column4
Row1 -1.437182  0.321864
Row2  0.845697 -0.561764
Row3  0.238974 -0.737501
Row4 -0.344307 -0.292289
Row5 -0.921085 -0.164013

In [25]:
df.loc['Row3']

Column1   -0.387098
Column2    0.238974
Column3   -0.284162
Column4   -0.737501
Name: Row3, dtype: float64

In [29]:
type(df.loc['Row3'])

pandas.core.series.Series

In [31]:
df.iloc[2:,1:]

Column2   Column3   Column4
Row3  0.238974 -0.284162 -0.737501
Row4 -0.344307 -0.277027 -0.292289
Row5 -0.921085  0.524528 -0.164013

In [32]:
df.iloc[2:,1:].values

array([[ 0.23897449, -0.28416202, -0.73750089],
       [-0.34430692, -0.27702676, -0.29228947],
       [-0.92108492,  0.52452812, -0.16401326]])

In [33]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [35]:
df.sum()

Column1    2.125968
Column2   -1.617902
Column3    0.552767
Column4   -1.433704
dtype: float64

In [38]:
df['Column1'].unique()

array([-0.67942333,  0.60107537, -0.38709783,  2.16143498,  0.42997914])